### ISSUE TITLE
Bug: dénomination objet 11774

### ISSUE THREAD

**Issue by tgicquel** [jflorant/suivi_projets#60]

**Comment by tgicquel** [comment]
Le (RELAI) GPM LE HAVRE_SERMETA-CHINE apparaît sous son n° et non sous son nom

**Comment by jflorant** [comment]
Corrigé !

**Comment by tgicquel** [comment]
Nickel!

________________________________
De : jflorant <notifications@github.com>
Envoyé : vendredi 14 décembre 2018 10:41
À : jflorant/suivi_projets
Cc : GICQUEL Tiphaine; Author
Objet : [NEWSLETTER] Re: [jflorant/suivi_projets] Bug: dénomination objet 11774 (#60)


Corrigé !

-
