### ISSUE TITLE
Bug: Liens capitalistiques

### ISSUE THREAD

**Issue by tgicquel** [jflorant/suivi_projets#61]
Comment se fait-il que les établissements secondaires de Navtis n'étaient pas dans la base de données (cf. import Diane)? Je les ai créés manuellement.

**Comment by jflorant** [comment]
Ils ont du sauter lors d'un des filtres ou n'existaient pas dans la base Diane au moment de l'import. La base Diane, même si elle est la meilleure source pour ce type d'infos, n'est pas exhaustive et est le résultat de croisements et d'enquêtes d'un bureau d'étude.
